name: BibTeX Validation

on:
  push:
    branches: [ main, gh-pages ]
    paths:
      - '*.bib'
  pull_request:
    branches: [ main, gh-pages ]
    paths:
      - '*.bib'

jobs:
  validate-bibtex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        
    - name: Install dependencies
      run: |
        gem install bibtex-ruby
        
    - name: Find BibTeX files
      id: find-bib
      run: |
        BIB_FILES=$(find . -name "*.bib" -not -path "./.git/*" | head -1)
        if [ -n "$BIB_FILES" ]; then
          echo "bib_file=$BIB_FILES" >> $GITHUB_OUTPUT
          echo "found=true" >> $GITHUB_OUTPUT
        else
          echo "found=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Validate BibTeX format
      if: steps.find-bib.outputs.found == 'true'
      run: |
        echo "Validating BibTeX file: ${{ steps.find-bib.outputs.bib_file }}"
        ruby lib/tidy_bibtex.rb --strict --check-author-commas "${{ steps.find-bib.outputs.bib_file }}" /tmp/validation_output.bib
        
    - name: Check for issues
      if: steps.find-bib.outputs.found == 'true'
      run: |
        echo "BibTeX validation completed successfully"
        echo "No unescaped % characters or author field issues found"
